name: Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build mynth-account container
        run: docker build -t docyogid/yog .

      - name: Publish container
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker push docyogid/yog:$TAG
        if: github.ref == 'refs/heads/main'
